[package]
name = "pulsar-ssd1306"
version = "0.1.0"
authors = ["Shane Vitarana <shanev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
